apiVersion: v1
kind: Namespace
metadata:
  name: disk-setup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: disk-setup
  namespace: disk-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disk-setup
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disk-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: disk-setup
subjects:
- kind: ServiceAccount
  name: disk-setup
  namespace: disk-setup
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-setup
  namespace: disk-setup
  labels:
    app: materialize-disk-setup
spec:
  selector:
    matchLabels:
      app: materialize-disk-setup
  template:
    metadata:
      labels:
        app: materialize-disk-setup
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: materialize.cloud/disk
                operator: In
                values: ["true"]
      tolerations:
        - key: "startup-taint.cluster-autoscaler.kubernetes.io/disk-unconfigured"
          operator: "Exists"
          effect: "NoSchedule"
      hostPID: true
      hostNetwork: true
      serviceAccountName: disk-setup
      initContainers:
        - name: disk-setup
          image: materialize/ephemeral-storage-setup-image:v0.4.0
          command: ["ephemeral-storage-setup"]
          args:
            - lvm
            - --cloud-provider
            - gcp
            - --remove-taint
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
              cpu: 50m
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: host-root
              mountPath: /host
      containers:
        - name: pause
          image: materialize/ephemeral-storage-setup-image:v0.4.0
          command: ["ephemeral-storage-setup"]
          args: ["sleep"]
          resources:
            limits:
              memory: 8Mi
            requests:
              memory: 8Mi
              cpu: 1m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
        - name: host-root
          hostPath:
            path: /
