default_install_hook_types:
  - pre-push
repos:
  - repo: local
    hooks:
      - id: shell-lint
        name: Shell Linting
        entry: shellcheck
        args: ["--external-sources", "--source-path=SCRIPTDIR"]
        language: system
        types: [shell]
