name: PR

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install cargo-deny
        run: >
          curl -Ls --fail https://github.com/EmbarkStudios/cargo-deny/releases/download/0.18.3/cargo-deny-0.18.3-x86_64-unknown-linux-musl.tar.gz
          | tar -xzC ~/.cargo/bin/ --strip-components 1 --no-anchored cargo-deny

      - name: Run linting
        run: ./bin/lint

  unit-tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: cargo test
        run: cargo test

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: docker build
        run: docker build .
